# Generated by Django 3.0.8 on 2021-01-09 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('isbn13', models.CharField(max_length=255)),
                ('isbn10', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('street_no', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=255)),
                ('identificator', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('delay_cost', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('extension_borrow', models.BooleanField(default=False)),
                ('extension_borrow_start', models.DateTimeField()),
                ('extension_borrow_end', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reader')),
            ],
        ),
    ]
