# Generated by Django 3.0.8 on 2021-01-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210109_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
