# Generated by Django 3.0.8 on 2021-01-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210109_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='street_no',
        ),
    ]
