# Generated by Django 3.0.8 on 2021-01-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_reader_street_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='identificator',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
