# Generated by Django 3.0.8 on 2021-01-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210109_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowbook',
            name='extension_borrow',
        ),
        migrations.RemoveField(
            model_name='borrowbook',
            name='extension_borrow_end',
        ),
        migrations.RemoveField(
            model_name='borrowbook',
            name='extension_borrow_start',
        ),
    ]
