# Generated by Django 3.0.8 on 2021-01-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210109_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
